# Generated by Django 6.0 on 2026-01-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Destaque na Home?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
