# Generated by Django 6.0 on 2026-01-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecao', '0003_remove_product_active_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
