# Generated by Django 6.0 on 2026-01-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.TextField(blank=True, null=True),
        ),
    ]
